apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dp
  labels:
    app: backend-app
    type: backend
spec:
  template:
    metadata:
      name: backend-dp
      labels:
        app: backend-app
        type: backend
    spec:
      containers:
        - name: backend-container
          image: nginx
  selector:
    matchLabels:
      app: backend-app
  replicas: 8
      