apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: vote-namespace
  labels:
    app: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      name: result-app
      labels:
        app: result-app
    spec:
      containers:
      - name: result-container
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80
          name: result-port