apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: vote-namespace
  labels:
    app: vote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      name: vote-app
      labels:
        app: vote-app
    spec:
      containers:
      - name: vote-container
        image: kodekloud/examplevotingapp_vote:v1
        ports:
        - containerPort: 80
          name: vote-port