apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: vote-namespace
  labels:
    app: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      name: worker-app
      labels:
        app: worker-app
    spec:
      containers:
        - name: worker-container
          image: dockersamples/examplevotingapp_worker
          command: ["sleep"]
          args: ["infinity"]