apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result-service
  namespace: vote-namespace
spec:
  type: NodePort
  ports:
  - name: result-service
    port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    app: result-app